= Enhancing Boot Application with Metrics

== Set up the Actuator

Spring Boot includes a number of additional features to help you monitor and manage your application when it’s pushed to production. These features are added by adding _spring-boot-starter-actuator_ to the classpath.  During our initial project setup with *start.spring.io* we've already included that.

. Verify the Spring Boot Actuator dependency in the following file: */cloud-native-spring/pom.xml*.  You should see the following dependency in the list:
+
[source, xml]
---------------------------------------------------------------------
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
---------------------------------------------------------------------

**Actuator Endpoint**

Now that we have set up our simple application, it is time to take a look at what Spring Actuator has to offer.

Actuator is a set of features that help you monitor and manage your application when it moves away from your local development environment and onto a test, staging or production environment. It helps expose operational information about the running application – health, metrics, audit entries, scheduled task, env settings, etc. You can query the information via either several HTTP endpoints or JMX beans. Being able to view the information is useful, but it’s hard to spot trends or see the behaviour over a period of time.

Micrometer is now the default metrics library in Spring Boot 2 and it doesn’t just give you metrics from your Spring application, but can also deliver JVM metrics (garbage collection and memory pools, etc) and also metrics from the application container. Micrometer has several different libraries that can be included to ship metrics to different backends and has support for Prometheus, Netflix Atlas, CloudWatch, Datadog, Graphite, Ganglia, JMX, Influx/Telegraf, New Relic, StatsD, SignalFx, and Wavefront.



 

. Run the updated application
+
[source,bash]
---------------------------------------------------------------------
$ mvn clean spring-boot:run
---------------------------------------------------------------------

In the browser, go to the URL http://localhost:8080/actuator/. This shows us an overview of the exposed Actuator endpoints. Compared to Spring Boot 1, the Actuator endpoints all reside after this Actuator endpoint. This should prevent naming collisions with your own endpoints whenever they would have the same name as Actuator endpoints. 

As you can see, only 3 Actuator endpoints are exposed by default. In order to expose more endpoints, we need to add an include or exclude configuration to the application.properties file. We will add all endpoints to the configuration, but you can also limit the exposed endpoints by means of a comma-separated list. In order to expose all endpoints, we add the following configuration to the application.properties file:


[source,bash]
---------------------------------------------------------------------
management.endpoints.web.exposure.include=*

---------------------------------------------------------------------

Restart the application and try out the following endpoints. The output is omitted here because it can be quite large:

http://localhost:8080/actuator/health

Displays Application and Datasource health information.  This can be customized based on application functionality.


**Secure the Endpoints**

Most of the time, we do not want this kind of information to be accessible by everyone. In that case, we can secure the Actuator endpoints. First of all, we will add Spring Security to the pom:

[source,bash]
---------------------------------------------------------------------
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-security</artifactId>
</dependency>
---------------------------------------------------------------------

Just by adding the above dependency Spring  Security presents us with a login page when trying to access the Actuator endpoints and also our own base endpoint. We can login with user *user* and the password which is available in the Spring Boot log. This looks like the following (of course the hash changes after each startup):

[source,bash]
---------------------------------------------------------------------
Using generated security password: 8da882c3-4bbb-4e71-88c2-13399d9f0724
---------------------------------------------------------------------
We can put our own user name and passwd also by adding the following lines to the application.properties file :

[source,bash]
---------------------------------------------------------------------
spring.security.user.name=pal
spring.security.user.password=pal123
spring.security.user.roles=ACTUATOR
---------------------------------------------------------------------

**The Actuator Health Endpoint**

The Actuator health endpoint, by default, shows no detail. Several built-in healthindicators are present, and the information to show is collected from these healthindicators. But by default, you will only see the following:


[source,bash]
---------------------------------------------------------------------
{
    "status": "UP"
}

---------------------------------------------------------------------

In order to see the information of the built-in healthindicators, we need to add the following line to your application.properties.  This way, all information from the retrieved healthindicators is being shown. The default value is never, never showing the health indicators information. We choose to show the health indicator information when an authorized user is requesting the information.

[source,bash]
---------------------------------------------------------------------
management.endpoint.health.show-details=when-authorized
---------------------------------------------------------------------

Re-run the application and invoke the Actuator health endpoint, the following information is shown in our case:

[source,bash]
---------------------------------------------------------------------
{
"status": "UP",
"details": {
"db": {
"status": "UP",
"details": {
"database": "H2",
"hello": 1
}
},
"diskSpace": {
"status": "UP",
"details": {
"total": 508828839936,
"free": 395953082368,
"threshold": 10485760
}
}
}
}
---------------------------------------------------------------------


. Create the class _io.pivotal.FlappingHealthIndicator_ (/cloud-native-spring/src/main/java/io/pivotal/FlappingHealthIndicator.java) and into it paste the following code:
+
[source,java]
---------------------------------------------------------------------
package io.pivotal;

import java.util.Random;

import org.springframework.boot.actuate.health.Health;
import org.springframework.boot.actuate.health.HealthIndicator;
import org.springframework.stereotype.Component;

@Component
public class FlappingHealthIndicator implements HealthIndicator {

    private Random random = new Random(System.currentTimeMillis());

    @Override
    public Health health() {
        int result = random.nextInt(100);
        if (result < 50) {
            return Health.down().withDetail("flapper", "failure").withDetail("random", result).build();
        } else {
            return Health.up().withDetail("flapper", "ok").withDetail("random", result).build();
        }
    }
}
---------------------------------------------------------------------
+
This demo health indicator will randomize the health check.

. Build and run the _cloud-native-spring_ application:
+
[source,bash]
---------------------------------------------------------------------
$ mvn clean spring-boot:run
---------------------------------------------------------------------

. Browse to http://localhost:8080/actuator/health and verify that the output is similar to the following (and changes randomly!).
+
[source,json]
---------------------------------------------------------------------
{
"status": "UP",
"details": {
"flapping": {
"status": "UP",
"details": {
"flapper": "ok",
"random": 51
}
},
"db": {
"status": "UP",
"details": {
"database": "H2",
"hello": 1
}
},
"diskSpace": {
"status": "UP",
"details": {
"total": 1000969428992,
"free": 631523762176,
"threshold": 10485760
}
}
}
}
---------------------------------------------------------------------

== Metrics

In Spring Boot 2.0, there has been a major rewrite regarding how the /metrics HTTP endpoint is designed. Most importantly, there’s now a dedicated project regarding metrics, called Micrometer.

Micrometer is a dimensional-first metrics collection facade whose aim is to allow you to time, count, and gauge your code with a vendor neutral API. Through classpath and configuration, you may select one or several monitoring systems to export your metrics data to. Think of it like SLF4J, but for metrics!

Before Spring Boot 2.0, metrics were single values, and organized in a tree-like way. Those are best described as hierarchical metrics. 

Spring Boot 2.0 provides an endpoint http://localhost:8080/actuator/metrics that exposes several automatically collected metrics for your application as a dimensional first view.

. Browse to http://localhost:8080/actuator/metrics. Review the metrics exposed.
+
[source,json]
---------------------------------------------------------------------
{
"names": [
"jvm.threads.states",
"http.server.requests",
"jdbc.connections.active",
"process.files.max",
"jvm.memory.used",
"jvm.gc.memory.promoted",
"jvm.memory.max",
"system.load.average.1m",
"jvm.gc.max.data.size",
"jdbc.connections.max",
"jdbc.connections.min",
"jvm.memory.committed",
"system.cpu.count",
"logback.events",
"tomcat.global.sent",
"jvm.gc.pause",
"jvm.buffer.memory.used",
"tomcat.sessions.created",
"jvm.threads.daemon",
"system.cpu.usage",
"jvm.gc.memory.allocated",
"tomcat.global.request.max",
"hikaricp.connections.idle",
"hikaricp.connections.pending",
"tomcat.global.request",
"tomcat.sessions.expired",
"hikaricp.connections",
"jvm.threads.live",
"jvm.threads.peak",
"tomcat.global.received",
"hikaricp.connections.active",
"hikaricp.connections.creation",
"process.uptime",
"tomcat.sessions.rejected",
"process.cpu.usage",
"tomcat.threads.config.max",
"jvm.classes.loaded",
"hikaricp.connections.max",
"hikaricp.connections.min",
"jvm.classes.unloaded",
"tomcat.global.error",
"tomcat.sessions.active.current",
"tomcat.sessions.alive.max",
"jvm.gc.live.data.size",
"hikaricp.connections.usage",
"tomcat.threads.current",
"hikaricp.connections.timeout",
"process.files.open",
"jvm.buffer.count",
"jvm.buffer.total.capacity",
"tomcat.sessions.active.max",
"hikaricp.connections.acquire",
"tomcat.threads.busy",
"process.start.time"
]
}
---------------------------------------------------------------------

To access a specific metric, we need to append the metric’s name to the path, e.g. /metrics/http.server.requests. The output looks like the following:
+
[source,json]
---------------------------------------------------------------------

"name": "http.server.requests",
"description": null,
"baseUnit": "seconds",
"measurements": [
{
"statistic": "COUNT",
"value": 5
},
{
"statistic": "TOTAL_TIME",
"value": 0.26881810500000003
},
{
"statistic": "MAX",
"value": 0
}
],
"availableTags": [
{
"tag": "exception",
"values": [
"None"
]
},
{
"tag": "method",
"values": [
"POST",
"GET"
]
},
{
"tag": "uri",
"values": [
"REDIRECTION",
"/actuator/metrics",
"root"
]
},
{
"tag": "outcome",
"values": [
"REDIRECTION",
"SUCCESS"
]
},
{
"tag": "status",
"values": [
"302",
"200"
]
}
]
}
---------------------------------------------------------------------



. Stop the cloud-native-spring application.

== Deploy _cloud-native-spring_ to Pivotal Cloud Foundry
. Build the application
+
[source,bash]
---------------------------------------------------------------------
$ mvn clean package
---------------------------------------------------------------------


+
[source, yaml]
---------------------------------------------------------------------
---
applications:
- name: cloud-native-spring
  host: cloud-native-spring-${random-word}
  memory: 512M
  instances: 1
  path: ./target/cloud-native-spring-0.0.1-SNAPSHOT-exec.jar
  buildpack: java_buildpack
  timeout: 180 # to give time for the data to import
  env:
    JAVA_OPTS: -Djava.security.egd=file:///dev/urandom
---------------------------------------------------------------------
. Push application into Cloud Foundry
+
$ mvn clean package
$ cf push -f manifest.yml


*Congratulations!* You’ve just learned how to add health and metrics to any Spring Boot application.
